# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'sitera'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'rules/node_exporter_alert.rules.yml'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mosquitto-exporter'
    static_configs:
      - targets: ['mosquitto-exporter:9234']
        labels:
          alias: mqtt

  - job_name: 'asterisk'
    metrics_path: asterisk/metrics
    static_configs:
      - targets: ['asterisk:8088']
        labels:
          alias: asterisk

  - job_name: 'haproxy'
    static_configs:
      - targets: ["haproxy:8405"]
        labels:
          alias: proxy

  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]
        labels:
          alias: host

  - job_name: 'cadvisor'
    static_configs:
      - targets: ["cadvisor:9110"]
        labels:
          alias: docker

  - job_name: 'app'
    metrics_path: prometheus
    static_configs:
      - targets: [ "app:8080","app:8081" ]
        labels:
          alias: app
